name: lib_graph
version: 0.1.0-dev
description: Graph Dart library dependencies
homepage: https://github.com/kevmoo/lib_graph
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  analyzer: ^0.30.0
  cli_util: ^0.1.0
  collection: ^1.14.1
  gviz: ^0.1.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
